# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: matheusmedeirosclemente
# "service" is the name of this project. This will also be added to your AWS resource names.
service: foodiary-jstack

plugins:
  - serverless-offline
provider:
  name: aws
  runtime: nodejs22.x
  region: us-east-1
  architecture: arm64
  timeout: 30
  environment:
    DATABASE_URL: ${env:DATABASE_URL}  
    JWT_SECRET: ${env:JWT_SECRET}
    BUCKET_NAME: !Ref UploadsBucket
  iam:
    role:
      statements:
        - Effect: Allow
          Action: 
            - s3:PutObject
          Resource: !Sub '${UploadsBucket.Arn}/*'
          

package:
  individually: true
build:
  esbuild:
    minify: true
    sourcemap: false

functions:
  signin:
    handler: src/functions/signin.handler
    events:
      - httpApi:
          path: /signin
          method: POST
  signup:
    handler: src/functions/signup.handler
    events:
      - httpApi:
          path: /signup
          method: POST
  me:
    handler: src/functions/me.handler
    events:
      - httpApi:
          path: /me
          method: GET

  CreateMeals:
    handler: src/functions/createMeal.handler
    events:
      - httpApi:
          path: /meal
          method: POST          

  ListMeals:
    handler: src/functions/ListMeals.handler
    events:
      - httpApi:
          path: /meals
          method: GET            
  getMealById:
    handler: src/functions/getMealById.handler
    events:
      - httpApi:
          method: GET
          path: /meals/{mealId} 

  fileUploadedEnvent:
    handler: src/functions/fileUploadedEvent.handler
    events:
      - s3:
          bucket: !Ref UploadsBucket
          event: s3:ObjectCreated:*
          existing: true
          forceDeploy: true

resources:
  Resources: 
    UploadsBucket: 
      Type: AWS::S3::Bucket
      Properties:
        BucketName: foodiary-mma-upload

    MealsQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: meals-queue
        VisibilityTimeout: 60
        RedrivePolicy:
          maxReceiveCount: 1
          deadLetterTargetArn: !GetAtt MealsDLQ.Arn
    MealsDLQ:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: meals-queue-dlq